TEST_MODE = True
LED_ENABLED = False

FACE_RECOGNITION_ENABLED = True
VOICE_ENABLED = True
LED_ENABLED = False

VOICE_LANGUAGE = "en-US"
LISTEN_TIMEOUT = 5
PHRASE_TIME_LIMIT = 7
MAX_VOICE_RETRIES = 3

AUTHORIZED_USERS = ["Karim", "Admin"]

LED_COUNT = 16
LED_PIN = 18
LED_FREQ_HZ = 800000
LED_DMA = 10
LED_BRIGHTNESS = 150
LED_INVERT = False
